version: '3.7'

services:
  
  process-engine:
    image: 5minds/process_engine_runtime
    networks:
      - process-engine
    ports:
      - 8001:8000

  jupyter-notebook:
    build:
      context: ./jupyter-notebook
      dockerfile: dockerfile-jupyter-notebook
    networks:
      - jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - notebooks:/home/jovyan/notebooks

  external-worker:
    build:
      context: ./external-worker
      dockerfile: dockerfile-external_worker
    networks:
      - process-engine
      - jupyter-notebook
    volumes:
      - notebooks:/usr/src/app/notebooks

networks: 
  process-engine:
  jupyter-notebook:

volumes:
  notebooks:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/external-worker/
      o: bind
