version: '3.7'

services:
  
  process-engine:
    image: 5minds/process_engine_runtime
    networks:
      - process-engine
    ports:
      - 8001:8000

  jupyter-notebook:
    build:
      context: ./jupyter-notebook
      dockerfile: dockerfile-jupyter-notebook
    networks:
      - jupyter-notebook
    ports:
      - "8888:8888"

networks: 
  process-engine:
  jupyter-notebook:

volumes:
  notebooks: {}
